name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        tag: ['2.10', latest]
        experimental: [false]
        include:
          - tag: dev
            experimental: true

    container:
      image:  google/dart:${{ matrix.tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Upgrade dependencies
      if: ${{ matrix.experimental }}
      run: dart pub upgrade

    - name: Install dependencies
      if: ${{ !matrix.experimental }}
      run: dart pub get

    - name: Check Stage formatting
      run: dart run bin/check_formatting.dart

    - name: Run tests
      run: dart test
