name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: ['2.10']

    container:
      image:  google/dart:${{ matrix.tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: dart pub get

    - name: Check Stage formatting
      run: dart run bin/check_formatting.dart

    - name: Run tests
      run: dart test
